/*
*
*   Generated by javascript
*   @file jquery.browser
*   @author TimYao <tmwoman@yeah.net>
*   @version 20160325
*
*   bug repair
*   基于jquery
*
*     修复  version>=1.9 last version 不支持$.browser问题
*
*   判断模式 $.browser
*
* */

(function($,global){
    if($===global.jQuery)
    {
        if($.browser)
        {
            return false;
        }
    }
    $.browser = (function(){
        var browser_v = {},
            P,
            browsers = navigator.userAgent;
        var uaMatch=function(a) {
            a = a.toLowerCase();
            a = /(webkit)[ \/]([\w.]+)/.exec(a) || /(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a) || /(msie) ([\w.]+)/.exec(a) || !/compatible/.test(a) && /(mozilla)(?:.*? rv:([\w.]+))?/.exec(a) || [];
            return {
                browser: a[1] || "",
                version: a[2] || "0"
            }
        };
        P = uaMatch(browsers);
        if(P.browser)
        {
            browser_v[P.browser] = true;
            browser_v['version'] = P.version;
        }
        if(browser_v.webkit)
        {
            browser_v.safari = P.browser.safari = true;
        }
        return browser_v;
    })();
})(jQuery,window);